const auth = {
  LOGIN_USER_BEGIN: 'LOGIN_USER_BEGIN',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  GET_USER_DATA: 'GET_USER_DATA',
  GET_USER_DATA_FAIL: 'GET_USER_DATA_FAIL',
};

export default auth;
