const commentTypes = {
  COMMENT_LOADING: 'COMMENT_LOADING',
  POST_COMMENT_SUCCESS: 'POST_COMMENT_SUCCESS',
  POST_COMMENT_ERROR: 'POST_COMMENT_ERROR',
  POST_THREAD_COMMENT: 'POST_THREAD_COMMENT'
};

export default commentTypes;
