const emailShareModalTypes = {
  OPEN_EMAIL_SHARE_MODAL: 'OPEN_EMAIL_SHARE_MODAL',
  CLOSE_EMAIL_SHARE_MODAL: 'CLOSE_EMAIL_SHARE_MODAL',
  EMAIL_SHARE_BEGINS: 'EMAIL_SHARE_BEGINS',
  EMAIL_SHARE_SUCCESS: 'EMAIL_SHARE_SUCCESS',
  EMAIL_SHARE_FAIL: 'EMAIL_SHARE_FAIL'
};
export default emailShareModalTypes;
