const profileActionTypes = {
  GET_PROFILE: 'GET_PROFILE',
  PROFILE_LOADING: 'PROFILE_LOADING',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  OPEN_READ_STATS_MODAL: 'OPEN_READ_STATS_MODAL',
  CLOSE_READ_STATS_MODAL: 'CLOSE_READ_STATS_MODAL'
};

export default profileActionTypes;
