const resetPassword = {
  CLOSE_FORGOT_MODAL: 'CLOSE_FORGOT_MODAL',
  OPEN_FORGOT_MODAL: 'OPEN_FORGOT_MODAL',
  FORGOT_PASSWORD_BEGIN: 'FORGOT_PASSWORD_BEGIN',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',
  RESET_PASSWORD_BEGIN: 'RESET_PASSWORD_BEGIN',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',
  GET_RESET_TOKEN: 'GET_RESET_TOKEN',
  OPEN_RESET_MODAL: 'OPEN_RESET_MODAL',
  CLOSE_RESET_MODAL: 'CLOSE_RESET_MODAL'
};

export default resetPassword;
